name: evaluapp
description: "An tool that helps you to evaluate your study performance"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  # firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  shared_preferences: ^2.0.15
  firebase_database: ^11.3.5
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  

flutter:
  uses-material-design: true

flutter_icons:
  image_path: 'assets/images/icon/icon.png'
  android: "launcher_icon"
  ios: true

